using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class POV_bullet : MonoBehaviour
{
    public float bulletSpeed, lifeTime;

    public Rigidbody theRigidbody;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        theRigidbody.velocity = transform.forward * bulletSpeed;

        lifeTime = Time.deltaTime;

        if(lifeTime <=0)
        {
            Destroy(gameObject);
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        Destroy(gameObject);
    }
}
